services:
  resume_parser_service:
    build: ./resume_parser_service
    container_name: resume_parser_service
    ports:
      - "8001:8001"
    depends_on:
      - postgres_db
      - mongo_db
    networks:
      - backend

  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: resume_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data:
  mongo_data:
