services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: "mongodb://mongodb:27017"  
    depends_on:
      mongodb:
        condition: service_healthy  

  mongodb:
    image: mongo:latest
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017 --quiet
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: